### ISSUE TITLE
Update README for new package name

### ISSUE THREAD

**Issue by cmoses8626** [tomscholz/meteor-jest-stubs#2]
`yarn add -D meteor-jest-stubs` adds `/node_modules/meteor-jest-stubs/lib`, but the README still mentions the original package's folder name (`jest-meteor-stubs/lib`) in the `modulePaths` stanza in the Usage example. 

Should be updated to:

`modulePaths: [
    '<rootDir>/node_modules/',
    '<rootDir>/node_modules/meteor-jest-stubs/lib/',
  ]`

**Comment by tomscholz** [comment]
Fixed in 1d67af124ebb64825dd8fdaaddb0066175a8426b :)
